// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -A --derive=Default --derive=PartialEq --smart-derive-elision -f snapshot.storage.k8s.io_volumesnapshotclasses.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use schemars::JsonSchema;
    pub use serde::{Serialize, Deserialize};
    pub use std::collections::BTreeMap;
}
use self::prelude::*;

