use std::borrow::Cow;
use std::collections::BTreeMap;

use chrono::{DateTime, Utc};
use k8s_openapi::api::core::v1::{Container, EnvFromSource, EnvVar, SecretKeySelector, Volume};
use k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::CustomResourceDefinition;
use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
use kube::{CustomResource, CustomResourceExt, Resource};
use schemars::{JsonSchema, Schema, SchemaGenerator};
use serde::{Deserialize, Serialize};
use strum::Display;
use url::Url;

use crate::selector::Selector;
use crate::validation::{
    budget_selector_not_empty, log_level, runner_immutable_fields, runner_max_cpu_greater_than_min,
    runner_max_memory_greater_than_min, workspace_auto_scale_bounds, workspace_clone_not_pooled,
    workspace_max_storage_greater_than_min, workspace_mode_no_downgrade,
    workspace_no_volume_with_name, workspace_restore_from_exclusive,
    workspace_restore_from_not_indexer_prefix,
};

use crate::{
    CpuQuantity, ResourceFactory, ResourceNameExt, ResourceOwnerRefExt, Result, StorageQuantity,
};

#[derive(Clone, Copy, Debug, Display, Eq, PartialEq, Serialize, Deserialize)]
pub enum LogLevel {
    #[strum(serialize = "debug")]
    Debug,
    #[strum(serialize = "info")]
    Info,
    #[strum(serialize = "warn")]
    Warn,
    #[strum(serialize = "error")]
    Error,
    #[strum(serialize = "critical")]
    Critical,
}

impl JsonSchema for LogLevel {
    fn schema_name() -> Cow<'static, str> {
        "LogLevel".into()
    }

    fn json_schema(_gen: &mut SchemaGenerator) -> Schema {
        schemars::json_schema!({"type": "string"})
    }
}

#[derive(Clone, Debug, Default, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct Requirement<T> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min: Option<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max: Option<T>,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct AutoScale {
    pub from: f64,
    pub to: f64,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct StorageRequirement {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min: Option<StorageQuantity>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max: Option<StorageQuantity>,
    /// DEPRECATED: only honoured in `Dedicated` mode. `Pooled` workspaces take
    /// their slot quota from `max`, so there is nothing to grow.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto: Option<AutoScale>,
}

/// How a workspace's files are stored.
#[derive(
    Clone, Copy, Debug, Default, Display, Deserialize, Serialize, JsonSchema, PartialEq, Eq,
)]
pub enum WorkspaceMode {
    /// One ReadWriteOnce PVC per workspace. Costs one volume attachment per
    /// workspace (Scaleway allows 15 per node) and gates the runner on volume
    /// provisioning.
    #[default]
    Dedicated,
    /// A slot on a shared per-node data volume, with S3 as the source of truth.
    /// One attachment per node regardless of workspace count.
    Pooled,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceIndexerPod {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<EnvVar>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub env_from: Option<Vec<EnvFromSource>>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceIndexer {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bucket: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key_prefix: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub upload_content: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pod: Option<WorkspaceIndexerPod>,
}

/// The slot a `Pooled` workspace occupies on a node's shared data volume.
/// Agent-owned; never set by clients.
///
/// Every field skips serializing when unset. These are written by more than one
/// field manager, and under server-side apply a serialized `null` is a claim on
/// the field, not an absence — so without this, whichever manager patched last
/// would blank the halves it does not own.
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceSlotStatus {
    /// Node whose data volume holds the slot.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    /// Opaque slot id. Generated by the node agent so a client can never steer
    /// the subPath it gets bind-mounted from.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Hard quota applied to the slot's XFS project.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quota: Option<StorageQuantity>,
}

/// The S3 archive backing a `Pooled` workspace.
///
/// Same field-manager caveat as [`WorkspaceSlotStatus`].
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceArchiveStatus {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key_prefix: Option<String>,
    /// Sum of tracked file sizes in the archive. Reported separately from
    /// `status.storage.used` (which stays disk-derived) because it is 10-100x
    /// smaller: it excludes the venv, gitignored files and anything outside
    /// the workspace directory.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_content_bytes: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_synced_at: Option<DateTime<Utc>>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceStatus {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub storage: Option<WorkspaceStorageStatus>,
    /// The materialized effective mode, resolved once on first reconcile and
    /// never changed afterwards. This is what makes flipping the operator's
    /// default mode safe: without it, changing the default would silently
    /// re-mode every existing workspace and orphan its PVC.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<WorkspaceMode>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slot: Option<WorkspaceSlotStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub archive: Option<WorkspaceArchiveStatus>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceStorageStatus {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used: Option<StorageQuantity>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub capacity: Option<StorageQuantity>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub available: Option<StorageQuantity>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceRestoreFrom {
    /// Bucket holding the source archive.
    pub bucket: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key_prefix: Option<String>,
    /// Env for the restore init container (AWS credentials), same shape as
    /// `indexer.pod`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pod: Option<WorkspaceIndexerPod>,
}

// Every optional field in this spec — and in the structs it nests — skips
// serializing when unset.
//
// Under server-side apply a serialized `null` is a claim on the field, not an
// absence. A client that fills in only the fields it cares about, which is what
// building a spec from `Default` produces, therefore ended up owning the whole
// tree: fields it never set were either taken over as empty, or the apply was
// refused outright with a conflict because another manager owned them. The
// controller, the platform and the indexer all write parts of a Workspace, so
// this was not hypothetical.
//
// It is not on its own protection against a *rollback*: relinquishing a field
// by omitting it deletes it just as surely as nulling it, once the manager
// owns it. Only writing under a manager name of one's own separates those two.
#[derive(CustomResource, Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[kube(
    group = "kubimo.aqora.io",
    version = "v1",
    kind = "Workspace",
    shortname = "bmow",
    namespaced,
    status = "WorkspaceStatus",
    validation = workspace_max_storage_greater_than_min(),
    validation = workspace_auto_scale_bounds(),
    validation = workspace_no_volume_with_name(),
    validation = workspace_restore_from_exclusive(),
    validation = workspace_restore_from_not_indexer_prefix(),
    validation = workspace_mode_no_downgrade(),
    validation = workspace_clone_not_pooled(),
)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceSpec {
    /// Storage backend for this workspace. Absent means `Dedicated`, so
    /// existing objects keep their current behaviour; the operator's
    /// `KUBIMO__DEFAULT_WORKSPACE_MODE` only applies to workspaces that have
    /// not yet materialized `status.mode`.
    ///
    /// This one had to skip before the rest, because it is an enum: the
    /// generated schema lists the permitted values, and an explicit `null` is
    /// not among them. Serializing it anyway made every spec built from
    /// `Default` — which is what the integration tests and any client that
    /// fills in only the fields it cares about produce — rejected outright with
    /// "Unsupported value: null". Nullable object fields tolerate it, so the
    /// breakage arrived with this field and went unnoticed while those tests
    /// were ignored.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<WorkspaceMode>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub storage: Option<StorageRequirement>,
    /// DEPRECATED: only honoured in `Dedicated` mode. `Pooled` workspaces have
    /// no init Job to run these in; seeding is expressed via `restoreFrom` or
    /// `cloneWorkspaceName` instead.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub init_containers: Option<Vec<Container>>,
    /// DEPRECATED: only ever applied to the init Job's pod, so it has no effect
    /// in `Pooled` mode.
    #[schemars(length(max = 25))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub volumes: Option<Vec<Volume>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub indexer: Option<WorkspaceIndexer>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub clone_workspace_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub restore_from: Option<WorkspaceRestoreFrom>,
}

#[derive(Clone, Copy, Debug, Display)]
pub enum WorkspaceField {
    #[strum(serialize = "metadata.name")]
    Name,
    #[strum(serialize = "metadata.namespace")]
    Namespace,
}

impl ResourceFactory for Workspace {
    fn new(name: &str, spec: Self::Spec) -> Self {
        Self::new(name, spec)
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct RunnerTls {
    pub hosts: Option<Vec<String>>,
    pub cluster_issuer: Option<String>,
    pub secret_name: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct RunnerIngress {
    pub class_name: Option<String>,
    pub path: Option<String>,
    pub tls: Option<RunnerTls>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct RunnerLifecycle {
    pub delete_after_secs_inactive: Option<u32>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default, Display)]
pub enum RunnerCommand {
    #[default]
    Edit,
    Run,
    Render,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RunnerStatus {
    pub conditions: Option<Vec<Condition>>,
    pub last_active: Option<DateTime<Utc>>,
    pub marimo_version: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct RunnerToken {
    pub value: Option<String>,
    pub secret_ref: Option<SecretKeySelector>,
}

#[derive(CustomResource, Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[kube(
    group = "kubimo.aqora.io",
    version = "v1",
    kind = "Runner",
    shortname = "bmor",
    selectable = ".spec.workspace",
    selectable = ".spec.command",
    namespaced,
    status = "RunnerStatus",
    validation = runner_immutable_fields(),
    validation = runner_max_memory_greater_than_min(),
    validation = runner_max_cpu_greater_than_min(),
    validation = log_level(),
)]
#[serde(rename_all = "camelCase")]
pub struct RunnerSpec {
    pub workspace: String,
    pub command: RunnerCommand,
    pub log_level: Option<LogLevel>,
    pub memory: Option<Requirement<StorageQuantity>>,
    pub cpu: Option<Requirement<CpuQuantity>>,
    pub env: Option<Vec<EnvVar>>,
    pub env_from: Option<Vec<EnvFromSource>>,
    pub ingress: Option<RunnerIngress>,
    pub lifecycle: Option<RunnerLifecycle>,
    pub token: Option<RunnerToken>,
    pub sidecars: Option<Vec<Container>>,
}

#[derive(Clone, Copy, Debug, Display)]
pub enum RunnerField {
    #[strum(serialize = "metadata.name")]
    Name,
    #[strum(serialize = "metadata.namespace")]
    Namespace,
    #[strum(serialize = "spec.workspace")]
    Workspace,
    #[strum(serialize = "spec.command")]
    Command,
}

impl ResourceFactory for Runner {
    fn new(name: &str, spec: Self::Spec) -> Self {
        Self::new(name, spec)
    }
}

impl Runner {
    pub fn ingress_tls_secret_name(&self) -> Option<&str> {
        self.spec
            .ingress
            .as_ref()?
            .tls
            .as_ref()?
            .secret_name
            .as_deref()
    }
}

impl Workspace {
    /// Which storage path this workspace takes.
    ///
    /// `status.mode` wins once set, so a workspace never changes mode because
    /// the operator's default changed. Only workspaces that have not yet
    /// materialized a mode fall through to `default_mode`.
    pub fn effective_mode(&self, default_mode: WorkspaceMode) -> WorkspaceMode {
        self.status
            .as_ref()
            .and_then(|status| status.mode)
            .or(self.spec.mode)
            .unwrap_or(default_mode)
    }

    pub fn new_runner(&self, name: &str, spec: RunnerSpec) -> Result<Runner> {
        let mut runner = Runner::new(
            name,
            RunnerSpec {
                workspace: self.name()?.to_string(),
                ..spec
            },
        );
        runner
            .meta_mut()
            .owner_references
            .get_or_insert_default()
            .push(self.static_controller_owner_ref()?);
        Ok(runner)
    }
}

#[derive(CustomResource, Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[kube(
    group = "kubimo.aqora.io",
    version = "v1",
    kind = "CacheJob",
    shortname = "bmocj",
    selectable = ".spec.workspace",
    namespaced,
    validation = log_level(),
)]
#[serde(rename_all = "camelCase")]
pub struct CacheJobSpec {
    pub workspace: String,
    pub log_level: Option<LogLevel>,
    pub memory: Option<Requirement<StorageQuantity>>,
    pub cpu: Option<Requirement<CpuQuantity>>,
    pub env: Option<Vec<EnvVar>>,
    pub env_from: Option<Vec<EnvFromSource>>,
    pub backoff_limit: Option<i32>,
}

#[derive(Clone, Copy, Debug, Display)]
pub enum CacheJobField {
    #[strum(serialize = "metadata.name")]
    Name,
    #[strum(serialize = "metadata.namespace")]
    Namespace,
    #[strum(serialize = "spec.workspace")]
    Workspace,
}

impl ResourceFactory for CacheJob {
    fn new(name: &str, spec: Self::Spec) -> Self {
        Self::new(name, spec)
    }
}

impl Workspace {
    pub fn new_cache_job(&self, name: &str, spec: CacheJobSpec) -> Result<CacheJob> {
        let mut cache_job = CacheJob::new(
            name,
            CacheJobSpec {
                workspace: self.name()?.to_string(),
                ..spec
            },
        );
        cache_job
            .meta_mut()
            .owner_references
            .get_or_insert_default()
            .push(self.static_controller_owner_ref()?);
        Ok(cache_job)
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct BudgetResourceStatus {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used: Option<StorageQuantity>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<StorageQuantity>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct BudgetStatus {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub storage: Option<BudgetResourceStatus>,
}

#[derive(CustomResource, Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[kube(
    group = "kubimo.aqora.io",
    version = "v1",
    kind = "Budget",
    shortname = "bmob",
    namespaced,
    status = "BudgetStatus",
    validation = budget_selector_not_empty(),
)]
#[serde(rename_all = "camelCase")]
pub struct BudgetSpec {
    /// matchLabels — objects whose labels are a superset of this map are governed by the budget.
    pub selector: BTreeMap<String, String>,
    /// Maximum total storage summed across all matching Workspaces. Only
    /// Workspaces that declare an explicit `spec.storage.min` count against and
    /// are constrained by this limit; storage-class-default Workspaces (no `min`)
    /// are neither sized nor refused here.
    pub storage: Option<StorageQuantity>,
}

impl BudgetSpec {
    /// Whether `labels` satisfy every entry in this budget's selector.
    pub fn matches(&self, labels: Option<&BTreeMap<String, String>>) -> bool {
        let Some(labels) = labels else {
            return self.selector.is_empty();
        };
        self.selector
            .iter()
            .all(|(key, value)| labels.get(key) == Some(value))
    }

    /// Equality label selector for listing the objects this budget governs.
    pub fn label_selector(&self) -> Selector {
        self.selector.iter().collect()
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceDirDirectory {
    pub name: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceDirSymlink {
    pub path: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceDirContentUrl {
    pub url: Url,
    pub crc32: Option<u32>,
    pub e_tag: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceDirMarimoCache {
    pub format: String,
    pub size: Option<u64>,
    pub created: Option<DateTime<Utc>>,
    pub modified: Option<DateTime<Utc>>,
    pub url: Option<WorkspaceDirContentUrl>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceDirMarimo {
    pub meta_json: Option<WorkspaceDirContentUrl>,
    pub caches: Option<Vec<WorkspaceDirMarimoCache>>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceDirFile {
    pub size: Option<u64>,
    pub content: Option<WorkspaceDirContentUrl>,
    pub marimo: Option<WorkspaceDirMarimo>,
}

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceDirEntry {
    pub name: String,
    pub created: Option<DateTime<Utc>>,
    pub modified: Option<DateTime<Utc>>,
    pub directory: Option<WorkspaceDirDirectory>,
    pub symlink: Option<WorkspaceDirSymlink>,
    pub file: Option<WorkspaceDirFile>,
}

#[derive(CustomResource, Clone, Debug, Deserialize, Serialize, JsonSchema, Default)]
#[kube(
    group = "kubimo.aqora.io",
    version = "v1",
    kind = "WorkspaceDirectory",
    root = "WorkspaceDir",
    shortname = "bmowd",
    selectable = ".spec.workspace",
    selectable = ".spec.path",
    namespaced
)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceDirSpec {
    pub workspace: String,
    pub path: String,
    pub entries: Option<Vec<WorkspaceDirEntry>>,
}

#[derive(Clone, Copy, Debug, Display)]
pub enum WorkspaceDirField {
    #[strum(serialize = "metadata.name")]
    Name,
    #[strum(serialize = "metadata.namespace")]
    Namespace,
    #[strum(serialize = "spec.workspace")]
    Workspace,
    #[strum(serialize = "spec.path")]
    Path,
}

impl ResourceFactory for WorkspaceDir {
    fn new(name: &str, spec: Self::Spec) -> Self {
        Self::new(name, spec)
    }
}

impl Workspace {
    pub fn new_workspace_directory(
        &self,
        name: &str,
        spec: WorkspaceDirSpec,
    ) -> Result<WorkspaceDir> {
        let mut workspace_directory = WorkspaceDir::new(
            name,
            WorkspaceDirSpec {
                workspace: self.name()?.to_string(),
                ..spec
            },
        );
        workspace_directory
            .meta_mut()
            .owner_references
            .get_or_insert_default()
            .push(self.static_controller_owner_ref()?);
        Ok(workspace_directory)
    }
}

pub fn all_crds() -> Vec<CustomResourceDefinition> {
    vec![
        Workspace::crd(),
        Runner::crd(),
        CacheJob::crd(),
        WorkspaceDir::crd(),
        Budget::crd(),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    fn labels(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    #[test]
    fn workspace_restore_from_serde() {
        let spec = WorkspaceSpec {
            restore_from: Some(WorkspaceRestoreFrom {
                bucket: "bucket".to_string(),
                key_prefix: Some("workspace/".to_string()),
                pod: None,
            }),
            ..Default::default()
        };
        let json = serde_json::to_value(&spec).unwrap();
        assert_eq!(json["restoreFrom"]["bucket"], "bucket");
        assert_eq!(json["restoreFrom"]["keyPrefix"], "workspace/");
        let parsed: WorkspaceSpec = serde_json::from_value(json).unwrap();
        assert_eq!(parsed.restore_from.unwrap().bucket, "bucket");
    }

    /// A status patch must never carry an explicit `null`.
    ///
    /// `status.slot` and `status.archive` are written by different field
    /// managers than `status.storage` and `status.mode`, and server-side apply
    /// treats a serialized `null` as "I own this field and it is empty". A
    /// partial write would therefore blank whatever another manager had set.
    #[test]
    fn a_partial_status_serializes_no_nulls() {
        let status = WorkspaceStatus {
            slot: Some(WorkspaceSlotStatus {
                node: Some("node-1".to_string()),
                ..Default::default()
            }),
            archive: Some(WorkspaceArchiveStatus {
                last_synced_at: Some(Utc::now()),
                ..Default::default()
            }),
            ..Default::default()
        };
        let json = serde_json::to_string(&status).unwrap();
        assert!(!json.contains("null"), "status patch had a null: {json}");
        assert!(json.contains("node-1"));
    }

    /// The same rule as [`a_partial_status_serializes_no_nulls`], for the spec.
    ///
    /// A spec is assembled from `Default` plus the handful of fields the caller
    /// actually has an opinion about. Serializing the rest as `null` made that
    /// apply a claim on the entire tree: fields the caller never set were taken
    /// over as empty, or the write was refused with a conflict because the
    /// controller or the indexer owned them.
    #[test]
    fn a_partial_spec_serializes_no_nulls() {
        let spec = WorkspaceSpec {
            storage: Some(StorageRequirement {
                min: Some("2Gi".parse().expect("a quantity")),
                ..Default::default()
            }),
            indexer: Some(WorkspaceIndexer {
                bucket: Some("archive".to_string()),
                pod: Some(WorkspaceIndexerPod::default()),
                ..Default::default()
            }),
            restore_from: Some(WorkspaceRestoreFrom {
                bucket: "seeds".to_string(),
                ..Default::default()
            }),
            ..Default::default()
        };
        let json = serde_json::to_string(&spec).unwrap();
        assert!(!json.contains("null"), "spec apply had a null: {json}");
        assert!(json.contains("2Gi"));
        assert!(json.contains("archive"));
    }

    /// A Runner's cpu and memory bounds, which are the same shape and are
    /// written by the same partial applies.
    #[test]
    fn a_partial_requirement_serializes_no_nulls() {
        let cpu = Requirement::<CpuQuantity> {
            min: Some("500m".parse().expect("a quantity")),
            max: None,
        };
        let json = serde_json::to_string(&cpu).unwrap();
        assert!(!json.contains("null"), "requirement had a null: {json}");
        assert!(json.contains("500m"));
    }

    #[test]
    fn workspace_crd_has_restore_from_validations() {
        let crd = serde_json::to_string(&Workspace::crd()).unwrap();
        assert!(crd.contains("restoreFrom"));
        assert!(crd.contains("restoreFrom and cloneWorkspaceName are mutually exclusive"));
        assert!(crd.contains("must not write to the restoreFrom archive location"));
    }

    fn workspace_with(
        spec_mode: Option<WorkspaceMode>,
        status_mode: Option<WorkspaceMode>,
    ) -> Workspace {
        let mut workspace = Workspace::new(
            "ws",
            WorkspaceSpec {
                mode: spec_mode,
                ..Default::default()
            },
        );
        workspace.status = Some(WorkspaceStatus {
            mode: status_mode,
            ..Default::default()
        });
        workspace
    }

    #[test]
    fn effective_mode_defaults_to_operator_default_when_unset() {
        let workspace = workspace_with(None, None);
        assert_eq!(
            workspace.effective_mode(WorkspaceMode::Dedicated),
            WorkspaceMode::Dedicated
        );
        assert_eq!(
            workspace.effective_mode(WorkspaceMode::Pooled),
            WorkspaceMode::Pooled
        );
    }

    #[test]
    fn effective_mode_prefers_spec_over_operator_default() {
        let workspace = workspace_with(Some(WorkspaceMode::Pooled), None);
        assert_eq!(
            workspace.effective_mode(WorkspaceMode::Dedicated),
            WorkspaceMode::Pooled
        );
    }

    /// The safety property behind flipping `KUBIMO__DEFAULT_WORKSPACE_MODE`:
    /// a workspace that already materialized a mode must never be re-moded by
    /// a change to the operator default, or its PVC would be orphaned.
    #[test]
    fn materialized_status_mode_pins_against_operator_default_change() {
        let workspace = workspace_with(None, Some(WorkspaceMode::Dedicated));
        assert_eq!(
            workspace.effective_mode(WorkspaceMode::Pooled),
            WorkspaceMode::Dedicated
        );
    }

    /// A workspace with no status at all (freshly created, never reconciled)
    /// must still resolve, not panic.
    #[test]
    fn effective_mode_handles_absent_status() {
        let workspace = Workspace::new("ws", WorkspaceSpec::default());
        assert_eq!(
            workspace.effective_mode(WorkspaceMode::Pooled),
            WorkspaceMode::Pooled
        );
    }

    /// The expression's shape is the contract, not just its presence: a
    /// workspace is Pooled whenever *either* its spec or its materialized status
    /// says so, and only an explicit Dedicated spec is refused.
    #[test]
    fn workspace_crd_has_mode_downgrade_validation() {
        let crd = serde_json::to_string(&Workspace::crd()).unwrap();
        assert!(crd.contains("cannot be changed back from Pooled to Dedicated"));

        let expression = include_str!("./validation/workspace_mode_no_downgrade.cel");
        assert!(
            expression.contains("oldSelf.status.mode == \"Pooled\""),
            "status.mode is materialized on every reconcile, so a Pooled workspace \
             need not say so in its spec"
        );
        // Refusing only an explicit Dedicated is what keeps those same
        // status-only-Pooled workspaces patchable at all: their spec has no mode,
        // so demanding `self.spec.mode == \"Pooled\"` would reject every apply.
        assert!(expression.contains("self.spec.mode == \"Dedicated\""));
    }

    /// `cloneWorkspaceName` is implemented only for `Dedicated` — `apply_pvc`
    /// and `apply_job` are its only readers and neither runs under `Pooled`.
    /// Before this rule the field was accepted and ignored, so a cloned pooled
    /// workspace came up empty with nothing reporting a problem.
    ///
    /// The expression is asserted rather than just the message because its shape
    /// is the contract: it must fire only when the mode is *explicitly* Pooled,
    /// so that a Dedicated workspace can still clone and a spec without a mode
    /// is not rejected on a guess about the operator's default.
    #[test]
    fn workspace_crd_refuses_clone_under_pooled() {
        let crd = serde_json::to_string(&Workspace::crd()).unwrap();
        assert!(
            crd.contains("cloneWorkspaceName is not supported for Pooled workspaces"),
            "the rule is missing from the generated CRD"
        );

        let expression = include_str!("./validation/workspace_clone_not_pooled.cel");
        // Explicitly Pooled + a clone is the rejected combination...
        assert!(expression.contains("self.spec.mode == \"Pooled\""));
        assert!(expression.contains("has(self.spec.cloneWorkspaceName)"));
        // ...and `has(self.spec.mode)` is what keeps a mode-less spec valid, so
        // the rule never rejects on an assumption about the operator default.
        assert!(
            expression.contains("has(self.spec.mode)"),
            "a spec without a mode must not be rejected: CEL cannot see \
             KUBIMO__DEFAULT_WORKSPACE_MODE, so that case stays uncaught by design"
        );
    }

    #[test]
    fn budget_matches_label_superset() {
        let budget = BudgetSpec {
            selector: labels(&[("user", "alice")]),
            storage: None,
        };
        // a superset of the selector matches
        assert!(budget.matches(Some(&labels(&[("user", "alice"), ("team", "x")]))));
        // exact match
        assert!(budget.matches(Some(&labels(&[("user", "alice")]))));
        // different value, missing key, and no labels do not match
        assert!(!budget.matches(Some(&labels(&[("user", "bob")]))));
        assert!(!budget.matches(Some(&labels(&[("team", "x")]))));
        assert!(!budget.matches(None));
    }
}
