FROM python:3.10-slim-bookworm AS base
RUN apt-get update \
  && apt-get install -y --no-install-recommends git ca-certificates \
  && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /workspace

FROM base AS init
COPY docker/setup /setup
