FROM rust:1.89-alpine3.22 AS build
RUN apk update && apk add musl-dev
WORKDIR /build
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
  --mount=type=cache,target=/usr/local/cargo/git \
  --mount=type=cache,target=target \
  cargo build --release -p kubimo-controller \
  && cp target/release/kubimo-controller /bin/kubimo-controller

FROM alpine:3.22
COPY --from=build /bin/kubimo-controller /bin/kubimo-controller
ENV RUST_LOG=info
CMD ["kubimo-controller"]
