[package]
name = "packer"
version = "0.1.0"
edition = "2024"

[dependencies]
ignore = { version = "0.4", features = ["simd-accel"] }
clap = { version = "4.5", features = ["derive"] }
tar = "0.4"
flate2 = "1.1"
thiserror = "2.0"

[dev-dependencies]
tempfile = "3.20"
