apiVersion: kubimo.aqora.io/v1
kind: Workspace
metadata:
  name: "workspace"
spec:
  storage:
    min: "10Gi"
---
apiVersion: kubimo.aqora.io/v1
kind: Runner
metadata:
  name: "editor"
spec:
  command: "Edit"
  workspace: "workspace"
  # lifecycle:
  #   deleteAfterSecsInactive: 60
  # ingress:
  #   tls:
  #     host: "kubimo.org"
  #     clusterIssuer: "letsencrypt-prod"
---
apiVersion: kubimo.aqora.io/v1
kind: Runner
metadata:
  name: "runner"
spec:
  command: "Run"
  workspace: "workspace"
  # lifecycle:
  #   deleteAfterSecsInactive: 60
  # ingress:
  #   tls:
  #     host: "kubimo.org"
  #     clusterIssuer: "letsencrypt-prod"
