apiVersion: kubimo.aqora.io/v1
kind: Workspace
metadata:
  name: "workspace"
spec:
  storage:
    min: "10Gi"
  indexer:
    schedule: "* * * * *"
    bucket: "bucket"
    keyPrefix: "workspace/"
    pod:
      env:
        - name: "AWS_ENDPOINT"
          value: "http://minio-tenant-hl.minio-tenant.svc.cluster.local:9000"
        - name: "AWS_REGION"
          value: "us-east-1"
        - name: "AWS_ALLOW_HTTP"
          value: "true"
        - name: "AWS_ACCESS_KEY_ID"
          value: "minioadmin"
        - name: "AWS_SECRET_ACCESS_KEY"
          value: "minioadmin"
---
apiVersion: kubimo.aqora.io/v1
kind: Runner
metadata:
  name: "editor"
spec:
  command: "Edit"
  workspace: "workspace"
  # token:
  #   value: "token"
  # lifecycle:
  #   deleteAfterSecsInactive: 60
  ingress:
    path: "/workspace/edit"
    # tls:
    #   hosts:
    #     - "example.com"
    #   clusterIssuer: "letsencrypt-prod"
---
apiVersion: kubimo.aqora.io/v1
kind: Runner
metadata:
  name: "runner"
spec:
  command: "Run"
  workspace: "workspace"
  # token:
  #   value: "token"
  # lifecycle:
  #   deleteAfterSecsInactive: 60
  ingress:
    path: "/workspace/run"
    # tls:
    #   hosts:
    #     - "example.com"
    #   clusterIssuer: "letsencrypt-prod"
---
apiVersion: kubimo.aqora.io/v1
kind: CacheJob
metadata:
  name: "cache"
spec:
  workspace: "workspace"
  backoffLimit: 0
