apiVersion: kubimo.aqora.io/v1
kind: Workspace
metadata:
  name: "workspace"
spec:
  storage:
    min: "10Gi"
---
apiVersion: kubimo.aqora.io/v1
kind: Runner
metadata:
  name: "editor"
spec:
  command: "Edit"
  workspace: "workspace"
  # token:
  #   value: "token"
  # lifecycle:
  #   deleteAfterSecsInactive: 60
  ingress:
    path: "/workspace/edit"
    # tls:
    #   host: "kubimo.org"
    #   clusterIssuer: "letsencrypt-prod"
---
apiVersion: kubimo.aqora.io/v1
kind: Runner
metadata:
  name: "runner"
spec:
  command: "Run"
  workspace: "workspace"
  # token:
  #   value: "token"
  # lifecycle:
  #   deleteAfterSecsInactive: 60
  ingress:
    path: "/workspace/run"
    # tls:
    #   host: "kubimo.org"
    #   clusterIssuer: "letsencrypt-prod"
