name: cd

on:
  push:
    branches:
      - main

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: cargo-cache-mount
          key: ${{ runner.os }}-cargo-cache-mount-${{ hashFiles('**/Cargo.lock') }}
      - name: Get version
        run: |
          export VERSION=$(grep -m1 '^version' Cargo.toml | sed -E 's/.*= *"([^"]+)".*/\1/')
          export VERSION_LIST="$(cut -d. -f1 <<<"$VERSION"),$(cut -d. -f1,2 <<<"$VERSION"),$VERSION,latest"
          echo "VERSION=$VERSION_LIST" >> $GITHUB_ENV
      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cargo-cache-mount
          dockerfile: docker/Dockerfile.controller
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          set: |
            marimo*.cache-from=type=registry,ref=ghcr.io/aqora-io/kubimo-marimo:latest
            controller*.cache-from=type=registry,ref=ghcr.io/aqora-io/kubimo-controller:latest
            *.cache-to=type=inline
          push: true

  charts:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Print CRDs
        run: |
          cargo run --package kubimo --example print_crds > charts/kubimo-controller/templates/crds.json
      - name: Update chart appVersion
        run: |
          export VERSION=$(grep -m1 '^version' Cargo.toml | sed -E 's/.*= *"([^"]+)".*/\1/')
          sed -i "s/{{ VERSION }}/$VERSION/" charts/kubimo-controller/Chart.yaml
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
