name: cd

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: cargo-cache-mount
          key: ${{ runner.os }}-cargo-cache-mount-${{ hashFiles('**/Cargo.lock') }}
      - name: Docker meta controller
        id: meta-controller
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/aqora-io/kubimo-controller
          bake-target: docker-metadata-controller
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Docker meta marimo
        id: meta-marimo
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/aqora-io/kubimo-marimo
          bake-target: docker-metadata-marimo
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cargo-cache-mount
          dockerfile: docker/Dockerfile.controller
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          set: |
            marimo*.cache-from=type=registry,ref=ghcr.io/aqora-io/kubimo-marimo:main
            controller*.cache-from=type=registry,ref=ghcr.io/aqora-io/kubimo-controller:main
            *.cache-to=type=inline
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta-controller.outputs.bake-file }}
            cwd://${{ steps.meta-marimo.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}

  charts:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Print CRDs
        run: |
          cargo run --package kubimo --example print_crds > charts/kubimo-controller/templates/crds.json
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
